<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/BS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from math import log, sqrt, exp
from scipy import stats


In [2]:
 import tensorflow as tf
tf.__version__

'1.12.0'

In [0]:
'''
Black-Scholes vanilla European call price function, with the default values as shown in the example in Hull (2009)
'''

def bs(S=42,K=40,R=0.1,Sigma=0.2,T=0.5):
    if ( np.any(S)==0 ):
        return 0
    elif (np.any(K)==0):
        return S    
    else:    
        d1 = (np.log(S/K)  +   (R+(np.square(Sigma)/2) )* T )  / (Sigma*np.sqrt(T))  
        d2 = d1 - (Sigma * np.sqrt(T) )   
        c = S*stats.norm.cdf(d1, 0.0, 1.0)-  K*np.exp(-R*T)*stats.norm.cdf(d2, 0.0, 1.0)
        return c  

In [6]:
bs()

4.759422392871532

In [0]:
BUSINESS_DAYS=252

In [0]:
NUMBER_S=10

In [0]:
INCREMENT_S=( 1/1 ) 

In [0]:
NUMBER_X=10

In [0]:
INCREMENT_X=1/1

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
NUMBER_T=BUSINESS_DAYS

In [0]:
INCREMENT_T=-int(BUSINESS_DAYS/12)

In [0]:
NUMBER_R=6

In [0]:
INCREMENT_R=1

In [0]:
optionS=np.array(np.arange(1,NUMBER_S+1,INCREMENT_S))

In [19]:
optionS

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionX=np.array(np.arange(1,NUMBER_X+1,INCREMENT_X))

In [21]:
optionX

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionR=np.array(np.arange(0,NUMBER_R+1,INCREMENT_R))

In [36]:
optionR

array([0, 1, 2, 3, 4, 5])

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [26]:
INCREMENT_SIGMA

1.0

In [0]:
optionSIGMA=np.array(np.arange(1,NUMBER_SIGMA+1,INCREMENT_SIGMA))

In [28]:
optionSIGMA

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionT=(np.arange(-INCREMENT_T,NUMBER_T-INCREMENT_T,-INCREMENT_T))

In [30]:
optionT

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
NUMBER_OPTIONS=NUMBER_S*NUMBER_X*NUMBER_SIGMA*int(-NUMBER_T/INCREMENT_T)*NUMBER_R

In [43]:
NUMBER_OPTIONS

72000

In [0]:
optionValue=np.zeros(NUMBER_OPTIONS)

In [0]:
optionDF=pd.DataFrame(index=np.arange(0,NUMBER_OPTIONS,1),columns=["S","X","R","Sigma","Time","Value"])

In [46]:
optionDF.shape

(72000, 6)

In [0]:
%%time
counter=0
print("S\tX\tR\tSigma\tTime\t\tValue")
for s in optionS:
    for x in optionX:
        for r in optionR:
            for sig in optionSIGMA:
                for t in optionT:
                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)
                    print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))
                    optionDF.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])
                    counter+=1  
