<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/BS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from math import log, sqrt, exp
from scipy import stats


In [0]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [0]:
#import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

SystemError: ignored

In [0]:
'''
Black-Scholes vanilla European call price function, with the default values as shown in the example in Hull (2009)
'''

def bs(S=42,K=40,R=0.1,Sigma=0.2,T=0.5):
    if ( np.any(S)==0 ):
        return 0
    elif (np.any(K)==0):
        return S    
    else:    
        d1 = (np.log(S/K)  +   (R+(np.square(Sigma)/2) )* T )  / (Sigma*np.sqrt(T))  
        d2 = d1 - (Sigma * np.sqrt(T) )   
        c = S*stats.norm.cdf(d1, 0.0, 1.0)-  K*np.exp(-R*T)*stats.norm.cdf(d2, 0.0, 1.0)
        return c  

In [0]:
bs()

4.759422392871532

In [0]:
u=np.arange(40,50,1)

In [0]:
u

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [0]:
%%time 
bs(u)

CPU times: user 225 µs, sys: 741 µs, total: 966 µs
Wall time: 1.11 ms


array([ 3.31112158,  4.00654253,  4.75942239,  5.56225965,  6.40747385,
        7.28782062,  8.1966803 ,  9.12822647, 10.07749334, 11.04036612])

In [0]:
%%time
for i in np.arange(40,50,1):
  v=(bs(i))

CPU times: user 3.55 ms, sys: 1.11 ms, total: 4.67 ms
Wall time: 3.97 ms


In [0]:
BUSINESS_DAYS=252

In [0]:
NUMBER_S=10

In [0]:
INCREMENT_S=( 1/1 ) 

In [0]:
NUMBER_X=10

In [0]:
INCREMENT_X=1/1

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
NUMBER_T=BUSINESS_DAYS

In [0]:
INCREMENT_T=-int(BUSINESS_DAYS/12)

In [0]:
NUMBER_R=6

In [0]:
INCREMENT_R=1

In [0]:
optionS=np.array(np.arange(1,NUMBER_S+1,INCREMENT_S))

In [0]:
optionS

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionX=np.array(np.arange(1,NUMBER_X+1,INCREMENT_X))

In [0]:
optionX

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionR=np.array(np.arange(0,NUMBER_R+1,INCREMENT_R))

In [0]:
optionR

array([0, 1, 2, 3, 4, 5, 6])

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
INCREMENT_SIGMA

1.0

In [0]:
optionSIGMA=np.array(np.arange(1,NUMBER_SIGMA+1,INCREMENT_SIGMA))

In [0]:
optionSIGMA

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionT=(np.arange(-INCREMENT_T,NUMBER_T-INCREMENT_T,-INCREMENT_T))

In [0]:
optionT

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
NUMBER_OPTIONS=NUMBER_S*NUMBER_X*NUMBER_SIGMA*int(-NUMBER_T/INCREMENT_T)*(NUMBER_R+1)

In [0]:
NUMBER_OPTIONS

84000

In [0]:
optionValue=np.zeros(NUMBER_OPTIONS)

In [0]:
optionDF2=pd.DataFrame(index=np.arange(0,NUMBER_OPTIONS,1),columns=["S","X","R","Sigma","Time","Value"])

In [0]:
optionDF2.shape

(84000, 6)

In [0]:
optionValue

array([0., 0., 0., ..., 0., 0., 0.])

In [0]:
s=np.repeat(optionS,NUMBER_OPTIONS/optionS.size)

In [0]:
optionS.size

10

In [0]:
s.shape

(84000,)

In [0]:
s[8350:8450]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [0]:
t=np.tile(optionT,7000)


In [0]:
t

array([ 21,  42,  63, ..., 210, 231, 252])

In [0]:
t[:25]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21])

In [0]:
t[-24:]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
t.size

84000

In [0]:
r=np.tile(np.repeat(optionR,12),1000)

In [0]:
r[0:500]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,

In [0]:
r.size

84000

In [0]:
sig=np.tile(np.repeat(optionSIGMA,84),100)

In [0]:
sig[80:90]

array([1., 1., 1., 1., 2., 2., 2., 2., 2., 2.])

In [0]:
x=np.tile(np.repeat(optionX,840),10)

In [0]:
x

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [0]:
x.size

84000

In [0]:
[]x[:100]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
optionDF3=pd.DataFrame(data={"S":s,"X":x,"Sigma":sig,"R":r,"T":t,"Value":v},index=np.arange(0,NUMBER_OPTIONS,1))

In [0]:
optionDF3=optionDF3[['S','X','Sigma','R','T','Value']]

In [0]:
v=np.zeros((NUMBER_OPTIONS))

In [0]:
optionDF3.shape

(84000, 6)

In [0]:
pd.set_option('display.max_rows',1000)
print(optionDF3[:850])

       S    X  Sigma  R    T  Value
0    1.0  1.0    1.0  0   21    0.0
1    1.0  1.0    1.0  0   42    0.0
2    1.0  1.0    1.0  0   63    0.0
3    1.0  1.0    1.0  0   84    0.0
4    1.0  1.0    1.0  0  105    0.0
5    1.0  1.0    1.0  0  126    0.0
6    1.0  1.0    1.0  0  147    0.0
7    1.0  1.0    1.0  0  168    0.0
8    1.0  1.0    1.0  0  189    0.0
9    1.0  1.0    1.0  0  210    0.0
10   1.0  1.0    1.0  0  231    0.0
11   1.0  1.0    1.0  0  252    0.0
12   1.0  1.0    1.0  1   21    0.0
13   1.0  1.0    1.0  1   42    0.0
14   1.0  1.0    1.0  1   63    0.0
15   1.0  1.0    1.0  1   84    0.0
16   1.0  1.0    1.0  1  105    0.0
17   1.0  1.0    1.0  1  126    0.0
18   1.0  1.0    1.0  1  147    0.0
19   1.0  1.0    1.0  1  168    0.0
20   1.0  1.0    1.0  1  189    0.0
21   1.0  1.0    1.0  1  210    0.0
22   1.0  1.0    1.0  1  231    0.0
23   1.0  1.0    1.0  1  252    0.0
24   1.0  1.0    1.0  2   21    0.0
25   1.0  1.0    1.0  2   42    0.0
26   1.0  1.0    1.0  2   63

In [0]:
%%time
optionValue=bs(s,x,r,sig,t/BUSINESS_DAYS)

CPU times: user 20 ms, sys: 2.17 ms, total: 22.2 ms
Wall time: 27.4 ms


In [0]:
 optionValue.size

84000

In [2]:
print(optionValue[80000:80500])

NameError: ignored

NameError: ignored

In [0]:
optionDF3.tail()

S     X  Sigma  R    T  Value
83995  10.0  10.0   10.0  6  168    0.0
83996  10.0  10.0   10.0  6  189    0.0
83997  10.0  10.0   10.0  6  210    0.0
83998  10.0  10.0   10.0  6  231    0.0
83999  10.0  10.0   10.0  6  252    0.0

In [0]:
f=open('optionDF3.csv', 'w')

In [0]:
optionDF3.to_csv('optionDF3.csv')

In [0]:
!pwd

/content


In [0]:
!ls -altr

total 2300
drwxr-xr-x 1 root root    4096 Dec 18 20:29 .config
drwxr-xr-x 1 root root    4096 Dec 18 20:29 sample_data
drwxr-xr-x 1 root root    4096 Dec 26 21:50 ..
-rw-r--r-- 1 root root       0 Dec 27 01:01 optionDF.csv
drwxr-xr-x 1 root root    4096 Dec 27 01:01 .
-rw-r--r-- 1 root root 2338111 Dec 27 01:01 optionDF3.csv


In [1]:
'''
Use the vectorised version of this function above, as this takes 16 mins with 84000 rows, but that function took only 250miliseconds
'''

'''
%%time
counter=0
#print("S\tX\tR\tSigma\tTime\t\tValue")
for s in optionS:
    for x in optionX:
        for r in optionR:
            for sig in optionSIGMA:
                for t in optionT:
                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)
                    #print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))
                    optionDF2.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])
                    counter+=1  
'''

'\n%%time\ncounter=0\n#print("S\tX\tR\tSigma\tTime\t\tValue")\nfor s in optionS:\n    for x in optionX:\n        for r in optionR:\n            for sig in optionSIGMA:\n                for t in optionT:\n                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)\n                    #print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))\n                    optionDF2.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])\n                    counter+=1  \n'