<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/BS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from math import log, sqrt, exp
from scipy import stats


In [2]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [3]:
#import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

SystemError: ignored

In [0]:
'''
Black-Scholes vanilla European call price function, with the default values as shown in the example in Hull (2009)
'''

def bs(S=42,K=40,R=0.1,Sigma=0.2,T=0.5):
    if ( np.any(S)==0 ):
        return 0
    elif (np.any(K)==0):
        return S    
    else:    
        d1 = (np.log(S/K)  +   (R+(np.square(Sigma)/2) )* T )  / (Sigma*np.sqrt(T))  
        d2 = d1 - (Sigma * np.sqrt(T) )   
        c = S*stats.norm.cdf(d1, 0.0, 1.0)-  K*np.exp(-R*T)*stats.norm.cdf(d2, 0.0, 1.0)
        return c  

In [5]:
bs()

4.759422392871532

In [0]:
u=np.arange(40,50,1)

In [7]:
u

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
%%time 
bs(u)

CPU times: user 225 µs, sys: 741 µs, total: 966 µs
Wall time: 1.11 ms


array([ 3.31112158,  4.00654253,  4.75942239,  5.56225965,  6.40747385,
        7.28782062,  8.1966803 ,  9.12822647, 10.07749334, 11.04036612])

In [10]:
%%time
for i in np.arange(40,50,1):
  v=(bs(i))

CPU times: user 3.55 ms, sys: 1.11 ms, total: 4.67 ms
Wall time: 3.97 ms


In [0]:
BUSINESS_DAYS=252

In [0]:
NUMBER_S=10

In [0]:
INCREMENT_S=( 1/1 ) 

In [0]:
NUMBER_X=10

In [0]:
INCREMENT_X=1/1

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
NUMBER_T=BUSINESS_DAYS

In [0]:
INCREMENT_T=-int(BUSINESS_DAYS/12)

In [0]:
NUMBER_R=6

In [0]:
INCREMENT_R=1

In [0]:
optionS=np.array(np.arange(1,NUMBER_S+1,INCREMENT_S))

In [24]:
optionS

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionX=np.array(np.arange(1,NUMBER_X+1,INCREMENT_X))

In [26]:
optionX

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionR=np.array(np.arange(0,NUMBER_R+1,INCREMENT_R))

In [28]:
optionR

array([0, 1, 2, 3, 4, 5, 6])

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
INCREMENT_SIGMA

1.0

In [0]:
optionSIGMA=np.array(np.arange(1,NUMBER_SIGMA+1,INCREMENT_SIGMA))

In [33]:
optionSIGMA

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionT=(np.arange(-INCREMENT_T,NUMBER_T-INCREMENT_T,-INCREMENT_T))

In [35]:
optionT

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
NUMBER_OPTIONS=NUMBER_S*NUMBER_X*NUMBER_SIGMA*int(-NUMBER_T/INCREMENT_T)*(NUMBER_R+1)

In [37]:
NUMBER_OPTIONS

84000

In [0]:
optionValue=np.zeros(NUMBER_OPTIONS)

In [0]:
optionDF2=pd.DataFrame(index=np.arange(0,NUMBER_OPTIONS,1),columns=["S","X","R","Sigma","Time","Value"])

In [0]:
optionDF2.shape

(84000, 6)

In [0]:
optionValue

array([0., 0., 0., ..., 0., 0., 0.])

In [0]:
optionValue=bs(optionS,optionX,optionR,optionSIGMA,optionT/BUSINESS_DAYS)

ValueError: ignored

In [0]:
s=np.repeat(optionS,NUMBER_OPTIONS/optionS.size)

In [40]:
optionS.size

10

In [41]:
s.shape

(84000,)

In [42]:
s[8350:8450]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [0]:
t=np.tile(optionT,7000)


In [44]:
t

array([ 21,  42,  63, ..., 210, 231, 252])

In [45]:
t[:25]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21])

In [50]:
t[-24:]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [51]:
t.size

84000

In [0]:
r=np.tile(np.repeat(optionR,12),1000)

In [69]:
r[0:500]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,

In [70]:
r.size

84000

In [0]:
sig=np.repeat(optionSIGMA,84)

In [72]:
sig

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  3.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3

In [0]:
optionDF

S   X  R Sigma       Time     Value
0       1   1  0     1  0.0833333  0.114766
1       1   1  0     1   0.166667  0.161744
2       1   1  0     1       0.25  0.197413
3       1   1  0     1   0.333333   0.22717
4       1   1  0     1   0.416667  0.253114
5       1   1  0     1        0.5  0.276326
6       1   1  0     1   0.583333  0.297451
7       1   1  0     1   0.666667  0.316909
8       1   1  0     1       0.75  0.334994
9       1   1  0     1   0.833333  0.351923
10      1   1  0     1   0.916667  0.367858
11      1   1  0     1          1  0.382925
12      1   1  0     2  0.0833333   0.22717
13      1   1  0     2   0.166667  0.316909
14      1   1  0     2       0.25  0.382925
15      1   1  0     2   0.333333  0.436297
16      1   1  0     2   0.416667  0.481395
17      1   1  0     2        0.5    0.5205
18      1   1  0     2   0.583333  0.554991
19      1   1  0     2   0.666667  0.585784
20      1   1  0     2       0.75  0.613524
21      1   1  0     2   0.833333   0.63869
22      1   1  0     2   0.916667  0.661648
23      1   1  0     2          1  0.682689
24      1   1  0     3  0.0833333  0.334994
25      1   1  0     3   0.166667  0.459709
26      1   1  0     3       0.25  0.546745
27      1   1  0     3   0.333333  0.613524
28      1   1  0     3   0.416667  0.667078
29      1   1  0     3        0.5  0.711156
...    ..  .. ..   ...        ...       ...
83970  10  10  6     8   0.583333    9.9966
83971  10  10  6     8   0.666667   9.99874
83972  10  10  6     8       0.75   9.99953
83973  10  10  6     8   0.833333   9.99983
83974  10  10  6     8   0.916667   9.99993
83975  10  10  6     8          1   9.99998
83976  10  10  6     9  0.0833333   8.50665
83977  10  10  6     9   0.166667    9.6091
83978  10  10  6     9       0.25    9.8894
83979  10  10  6     9   0.333333   9.96753
83980  10  10  6     9   0.416667   9.99026
83981  10  10  6     9        0.5   9.99703
83982  10  10  6     9   0.583333   9.99909
83983  10  10  6     9   0.666667   9.99972
83984  10  10  6     9       0.75   9.99991
83985  10  10  6     9   0.833333   9.99997
83986  10  10  6     9   0.916667   9.99999
83987  10  10  6     9          1        10
83988  10  10  6    10  0.0833333   8.85142
83989  10  10  6    10   0.166667   9.75552
83990  10  10  6    10       0.25   9.94343
83991  10  10  6    10   0.333333   9.98638
83992  10  10  6    10   0.416667   9.99665
83993  10  10  6    10        0.5   9.99916
83994  10  10  6    10   0.583333   9.99979
83995  10  10  6    10   0.666667   9.99995
83996  10  10  6    10       0.75   9.99999
83997  10  10  6    10   0.833333        10
83998  10  10  6    10   0.916667        10
83999  10  10  6    10          1        10

[84000 rows x 6 columns]

In [0]:
optionDF.tail

<bound method NDFrame.tail of         S   X  R Sigma       Time     Value
0       1   1  0     1  0.0833333  0.114766
1       1   1  0     1   0.166667  0.161744
2       1   1  0     1       0.25  0.197413
3       1   1  0     1   0.333333   0.22717
4       1   1  0     1   0.416667  0.253114
5       1   1  0     1        0.5  0.276326
6       1   1  0     1   0.583333  0.297451
7       1   1  0     1   0.666667  0.316909
8       1   1  0     1       0.75  0.334994
9       1   1  0     1   0.833333  0.351923
10      1   1  0     1   0.916667  0.367858
11      1   1  0     1          1  0.382925
12      1   1  0     2  0.0833333   0.22717
13      1   1  0     2   0.166667  0.316909
14      1   1  0     2       0.25  0.382925
15      1   1  0     2   0.333333  0.436297
16      1   1  0     2   0.416667  0.481395
17      1   1  0     2        0.5    0.5205
18      1   1  0     2   0.583333  0.554991
19      1   1  0     2   0.666667  0.585784
20      1   1  0     2       0.75  0.613524
21

In [0]:
optionDF.tail()

S   X  R Sigma      Time    Value
83995  10  10  6    10  0.666667  9.99995
83996  10  10  6    10      0.75  9.99999
83997  10  10  6    10  0.833333       10
83998  10  10  6    10  0.916667       10
83999  10  10  6    10         1       10

In [0]:
f=open('optionDF.csv', 'w')

In [0]:
optionDF.to_csv('optionDF.csv')

In [0]:
!pwd

/content


In [0]:
!ls -altr

total 4348
drwxr-xr-x 1 root root    4096 Dec 18 20:29 .config
drwxr-xr-x 1 root root    4096 Dec 18 20:29 sample_data
drwxr-xr-x 1 root root    4096 Dec 24 20:26 ..
drwxr-xr-x 1 root root    4096 Dec 24 22:35 .
-rw-r--r-- 1 root root 4435738 Dec 24 22:42 optionDF.csv


In [0]:
 
%%time
counter=0
#print("S\tX\tR\tSigma\tTime\t\tValue")
for s in optionS:
    for x in optionX:
        for r in optionR:
            for sig in optionSIGMA:
                for t in optionT:
                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)
                    #print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))
                    optionDF2.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])
                    counter+=1  


CPU times: user 16min 18s, sys: 4.56 s, total: 16min 23s
Wall time: 16min 23s
