<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/BS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from math import log, sqrt, exp
from scipy import stats


In [95]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [96]:
#import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

SystemError: ignored

In [0]:
'''
Black-Scholes vanilla European call price function, with the default values as shown in the example in Hull (2009)
'''

def bs(S=42,K=40,R=0.1,Sigma=0.2,T=0.5):
    if ( np.any(S)==0 ):
        return 0
    elif (np.any(K)==0):
        return S    
    else:    
        d1 = (np.log(S/K)  +   (R+(np.square(Sigma)/2) )* T )  / (Sigma*np.sqrt(T))  
        d2 = d1 - (Sigma * np.sqrt(T) )   
        c = S*stats.norm.cdf(d1, 0.0, 1.0)-  K*np.exp(-R*T)*stats.norm.cdf(d2, 0.0, 1.0)
        return c  

In [98]:
bs()

4.759422392871532

In [0]:
u=np.arange(40,50,1)

In [100]:
u

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [101]:
%%time 
bs(u)

CPU times: user 1.23 ms, sys: 856 µs, total: 2.09 ms
Wall time: 1.56 ms


array([ 3.31112158,  4.00654253,  4.75942239,  5.56225965,  6.40747385,
        7.28782062,  8.1966803 ,  9.12822647, 10.07749334, 11.04036612])

In [102]:
%%time
for i in np.arange(40,50,1):
  v=(bs(i))

CPU times: user 4.31 ms, sys: 868 µs, total: 5.18 ms
Wall time: 6.16 ms


In [0]:
BUSINESS_DAYS=252

In [0]:
NUMBER_S=10

In [0]:
INCREMENT_S=( 1/1 ) 

In [0]:
NUMBER_X=10

In [0]:
INCREMENT_X=1/1

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
NUMBER_T=BUSINESS_DAYS

In [0]:
INCREMENT_T=-int(BUSINESS_DAYS/12)

In [0]:
NUMBER_R=6

In [0]:
INCREMENT_R=1

In [0]:
optionS=np.array(np.arange(1,NUMBER_S+1,INCREMENT_S))

In [115]:
optionS

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionX=np.array(np.arange(1,NUMBER_X+1,INCREMENT_X))

In [117]:
optionX

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionR=np.array(np.arange(0,NUMBER_R+1,INCREMENT_R))

In [119]:
optionR

array([0, 1, 2, 3, 4, 5, 6])

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [122]:
INCREMENT_SIGMA

1.0

In [0]:
optionSIGMA=np.array(np.arange(1,NUMBER_SIGMA+1,INCREMENT_SIGMA))

In [124]:
optionSIGMA

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionT=(np.arange(-INCREMENT_T,NUMBER_T-INCREMENT_T,-INCREMENT_T))

In [126]:
optionT

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
NUMBER_OPTIONS=NUMBER_S*NUMBER_X*NUMBER_SIGMA*int(-NUMBER_T/INCREMENT_T)*(NUMBER_R+1)

In [128]:
NUMBER_OPTIONS

84000

In [0]:
optionValue=np.zeros(NUMBER_OPTIONS)

In [0]:
optionDF2=pd.DataFrame(index=np.arange(0,NUMBER_OPTIONS,1),columns=["S","X","R","Sigma","Time","Value"])

In [43]:
optionDF2.shape

(84000, 6)

In [44]:
optionValue

array([0., 0., 0., ..., 0., 0., 0.])

In [0]:
s=np.repeat(optionS,NUMBER_OPTIONS/optionS.size)

In [46]:
optionS.size

10

In [47]:
s.shape

(84000,)

In [48]:
s[8350:8450]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [0]:
t=np.tile(optionT,NUMBER_OPTIONS//optionT.size)


In [132]:
t

array([ 21,  42,  63, ..., 210, 231, 252])

In [133]:
t[:25]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21])

In [134]:
t[-24:]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [135]:
t.size

84000

In [0]:
r=np.tile(np.repeat(optionR,optionT.size),NUMBER_OPTIONS//(optionT.size*optionR.size))

In [144]:
r[0:500]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,

In [145]:
r.size

84000

In [0]:
sig=np.tile(np.repeat(optionSIGMA,84),100)

In [61]:
sig[80:90]

array([1., 1., 1., 1., 2., 2., 2., 2., 2., 2.])

In [0]:
x=np.tile(np.repeat(optionX,840),10)

In [64]:
x

array([ 1.,  1.,  1., ..., 10., 10., 10.])

In [65]:
x.size

84000

In [67]:
x[:100]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
optionDF3=pd.DataFrame(data={"S":s,"X":x,"Sigma":sig,"R":r,"T":t,"Value":v},index=np.arange(0,NUMBER_OPTIONS,1))

In [0]:
optionDF3=optionDF3[['S','X','Sigma','R','T','Value']]

In [0]:
v=np.zeros((NUMBER_OPTIONS))

In [72]:
optionDF3.shape

(84000, 6)

In [84]:
pd.set_option('display.max_rows',1000)
print(optionDF3[:850])

       S    X  Sigma  R    T  Value
0    1.0  1.0    1.0  0   21    0.0
1    1.0  1.0    1.0  0   42    0.0
2    1.0  1.0    1.0  0   63    0.0
3    1.0  1.0    1.0  0   84    0.0
4    1.0  1.0    1.0  0  105    0.0
5    1.0  1.0    1.0  0  126    0.0
6    1.0  1.0    1.0  0  147    0.0
7    1.0  1.0    1.0  0  168    0.0
8    1.0  1.0    1.0  0  189    0.0
9    1.0  1.0    1.0  0  210    0.0
10   1.0  1.0    1.0  0  231    0.0
11   1.0  1.0    1.0  0  252    0.0
12   1.0  1.0    1.0  1   21    0.0
13   1.0  1.0    1.0  1   42    0.0
14   1.0  1.0    1.0  1   63    0.0
15   1.0  1.0    1.0  1   84    0.0
16   1.0  1.0    1.0  1  105    0.0
17   1.0  1.0    1.0  1  126    0.0
18   1.0  1.0    1.0  1  147    0.0
19   1.0  1.0    1.0  1  168    0.0
20   1.0  1.0    1.0  1  189    0.0
21   1.0  1.0    1.0  1  210    0.0
22   1.0  1.0    1.0  1  231    0.0
23   1.0  1.0    1.0  1  252    0.0
24   1.0  1.0    1.0  2   21    0.0
25   1.0  1.0    1.0  2   42    0.0
26   1.0  1.0    1.0  2   63

In [81]:
%%time
optionValue=bs(s,x,r,sig,t/BUSINESS_DAYS)

CPU times: user 18.8 ms, sys: 10.6 ms, total: 29.4 ms
Wall time: 31.8 ms


In [82]:
 optionValue.size

84000

In [83]:
print(optionValue[80000:80500])

[9.40781879 9.52722074 9.62174686 9.69682491 5.9113766  7.12095963
 7.92210241 8.48006899 8.87867026 9.16778794 9.37962139 9.53594722
 9.65193    9.73833891 9.80292815 9.851338   6.16876553 7.46166536
 8.27793138 8.81708752 9.18115742 9.43019007 9.60196907 9.7211555
 9.80420779 9.86227117 9.90296927 9.93155496 6.41696745 7.7742065
 8.58641879 9.09225579 9.41323005 9.61906172 9.75193642 9.83810135
 9.89415675 9.93071144 9.95459307 9.97021767 6.65522913 8.05808171
 8.84976948 9.31225758 9.58660633 9.75069563 9.84932435 9.90879615
 9.94473454 9.96648496 9.97966316 9.98765411 5.78281185 6.86271245
 7.58379135 8.10405308 8.49436718 8.79418952 9.02818113 9.21288822
 9.3599481  9.47782123 9.57280968 9.64969484 6.00369421 7.16203723
 7.91148949 8.43338286 8.81042809 9.08893897 9.29775014 9.45598672
 9.57686783 9.66979504 9.74159467 9.79730092 6.21959262 7.44465945
 8.20914083 8.72056021 9.07469617 9.32505697 9.50452542 9.63446249
 9.72924651 9.79879402 9.85006508 9.88800901 6.42991491 7.709557

In [0]:
optionDF3['Value']=optionValue

In [89]:
optionDF3

S     X  Sigma  R    T      Value
0       1.0   1.0    1.0  0   21   0.114766
1       1.0   1.0    1.0  0   42   0.161744
2       1.0   1.0    1.0  0   63   0.197413
3       1.0   1.0    1.0  0   84   0.227170
4       1.0   1.0    1.0  0  105   0.253114
5       1.0   1.0    1.0  0  126   0.276326
6       1.0   1.0    1.0  0  147   0.297451
7       1.0   1.0    1.0  0  168   0.316909
8       1.0   1.0    1.0  0  189   0.334994
9       1.0   1.0    1.0  0  210   0.351923
10      1.0   1.0    1.0  0  231   0.367858
11      1.0   1.0    1.0  0  252   0.382925
12      1.0   1.0    1.0  1   21   0.154680
13      1.0   1.0    1.0  1   42   0.238157
14      1.0   1.0    1.0  1   63   0.307100
15      1.0   1.0    1.0  1   84   0.367109
16      1.0   1.0    1.0  1  105   0.420487
17      1.0   1.0    1.0  1  126   0.468512
18      1.0   1.0    1.0  1  147   0.512017
19      1.0   1.0    1.0  1  168   0.551603
20      1.0   1.0    1.0  1  189   0.587731
21      1.0   1.0    1.0  1  210   0.620777
22      1.0   1.0    1.0  1  231   0.651050
23      1.0   1.0    1.0  1  252   0.678818
24      1.0   1.0    1.0  2   21   0.199733
25      1.0   1.0    1.0  2   42   0.323319
26      1.0   1.0    1.0  2   63   0.425276
27      1.0   1.0    1.0  2   84   0.511337
28      1.0   1.0    1.0  2  105   0.584454
29      1.0   1.0    1.0  2  126   0.646701
30      1.0   1.0    1.0  2  147   0.699720
31      1.0   1.0    1.0  2  168   0.744874
32      1.0   1.0    1.0  2  189   0.783314
33      1.0   1.0    1.0  2  210   0.816025
34      1.0   1.0    1.0  2  231   0.843845
35      1.0   1.0    1.0  2  252   0.867496
36      1.0   1.0    1.0  3   21   0.248246
37      1.0   1.0    1.0  3   42   0.410183
38      1.0   1.0    1.0  3   63   0.537480
39      1.0   1.0    1.0  3   84   0.637858
40      1.0   1.0    1.0  3  105   0.716829
41      1.0   1.0    1.0  3  126   0.778807
42      1.0   1.0    1.0  3  147   0.827353
43      1.0   1.0    1.0  3  168   0.865321
44      1.0   1.0    1.0  3  189   0.894984
45      1.0   1.0    1.0  3  210   0.918139
46      1.0   1.0    1.0  3  231   0.936203
47      1.0   1.0    1.0  3  252   0.950289
48      1.0   1.0    1.0  4   21   0.298397
49      1.0   1.0    1.0  4   42   0.492774
50      1.0   1.0    1.0  4   63   0.634633
51      1.0   1.0    1.0  4   84   0.737423
52      1.0   1.0    1.0  4  105   0.811541
53      1.0   1.0    1.0  4  126   0.864835
54      1.0   1.0    1.0  4  147   0.903098
55      1.0   1.0    1.0  4  168   0.930546
56      1.0   1.0    1.0  4  189   0.950225
57      1.0   1.0    1.0  4  210   0.964331
58      1.0   1.0    1.0  4  231   0.974441
59      1.0   1.0    1.0  4  252   0.981685
60      1.0   1.0    1.0  5   21   0.348507
61      1.0   1.0    1.0  5   42   0.567413
62      1.0   1.0    1.0  5   63   0.714018
63      1.0   1.0    1.0  5   84   0.811262
64      1.0   1.0    1.0  5  105   0.875522
65      1.0   1.0    1.0  5  126   0.917925
66      1.0   1.0    1.0  5  147   0.945889
67      1.0   1.0    1.0  5  168   0.964327
68      1.0   1.0    1.0  5  189   0.976482
69      1.0   1.0    1.0  5  210   0.984496
70      1.0   1.0    1.0  5  231   0.989779
71      1.0   1.0    1.0  5  252   0.993262
72      1.0   1.0    1.0  6   21   0.397241
73      1.0   1.0    1.0  6   42   0.632690
74      1.0   1.0    1.0  6   63   0.776958
75      1.0   1.0    1.0  6   84   0.864679
76      1.0   1.0    1.0  6  105   0.917917
77      1.0   1.0    1.0  6  126   0.950213
78      1.0   1.0    1.0  6  147   0.969803
79      1.0   1.0    1.0  6  168   0.981684
80      1.0   1.0    1.0  6  189   0.988891
81      1.0   1.0    1.0  6  210   0.993262
82      1.0   1.0    1.0  6  231   0.995913
83      1.0   1.0    1.0  6  252   0.997521
84      1.0   1.0    2.0  0   21   0.227170
85      1.0   1.0    2.0  0   42   0.316909
86      1.0   1.0    2.0  0   63   0.382925
87      1.0   1.0    2.0  0   84   0.436297
88      1.0   1.0    2.0  0  105   0.481395
89      1.0   1.0    2.0  0  126   0.520500
90    

NameError: ignored

In [0]:
optionDF3.tail()

S     X  Sigma  R    T  Value
83995  10.0  10.0   10.0  6  168    0.0
83996  10.0  10.0   10.0  6  189    0.0
83997  10.0  10.0   10.0  6  210    0.0
83998  10.0  10.0   10.0  6  231    0.0
83999  10.0  10.0   10.0  6  252    0.0

In [0]:
f=open('optionDF3.csv', 'w')

In [0]:
optionDF3.to_csv('optionDF3.csv')

In [92]:
!pwd

/content


In [93]:
!ls -altr

total 3476
drwxr-xr-x 1 root root    4096 Dec 18 20:29 .config
drwxr-xr-x 1 root root    4096 Dec 18 20:29 sample_data
drwxr-xr-x 1 root root    4096 Dec 27 19:19 ..
drwxr-xr-x 1 root root    4096 Dec 27 20:07 .
-rw-r--r-- 1 root root 3539735 Dec 27 20:07 optionDF3.csv


In [1]:
'''
Use the vectorised version of this function above, as this takes 16 mins with 84000 rows, but that function took only 250miliseconds
'''

'''
%%time
counter=0
#print("S\tX\tR\tSigma\tTime\t\tValue")
for s in optionS:
    for x in optionX:
        for r in optionR:
            for sig in optionSIGMA:
                for t in optionT:
                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)
                    #print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))
                    optionDF2.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])
                    counter+=1  
'''

'\n%%time\ncounter=0\n#print("S\tX\tR\tSigma\tTime\t\tValue")\nfor s in optionS:\n    for x in optionX:\n        for r in optionR:\n            for sig in optionSIGMA:\n                for t in optionT:\n                    optionValue[counter]=bs(S=s,K=x,R=r,Sigma=sig,T=t/BUSINESS_DAYS)\n                    #print("{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3.2f}\t{:3f}\t{:3.5f}\n".format(s,x,r,sig,t,optionValue[counter]))\n                    optionDF2.loc[counter]=(s,x,r,sig,t/BUSINESS_DAYS,optionValue[counter])\n                    counter+=1  \n'