<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/BS3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from math import log, sqrt, exp
from scipy import stats


In [5]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [6]:
#import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

SystemError: ignored

In [0]:
'''
Black-Scholes vanilla European call price function, with the default values as shown in the example in Hull (2009)
'''

def bs(S=42,K=40,R=0.1,Sigma=0.2,T=0.5):
    if ( np.any(S)==0 ):
        return 0
    elif (np.any(K)==0):
        return S    
    else:    
        d1 = (np.log(S/K)  +   (R+(np.square(Sigma)/2) )* T )  / (Sigma*np.sqrt(T))  
        d2 = d1 - (Sigma * np.sqrt(T) )   
        c = S*stats.norm.cdf(d1, 0.0, 1.0)-  K*np.exp(-R*T)*stats.norm.cdf(d2, 0.0, 1.0)
        return c  

In [8]:
bs()

4.759422392871532

In [0]:
BUSINESS_DAYS=252

In [0]:
NUMBER_S=50

In [0]:
INCREMENT_S=( 1/1 ) 

In [0]:
NUMBER_X=50

In [0]:
INCREMENT_X=1/1

In [0]:
NUMBER_SIGMA=50

In [0]:
INCREMENT_SIGMA=1/1

In [0]:
NUMBER_T=BUSINESS_DAYS

In [0]:
INCREMENT_T=-int(BUSINESS_DAYS/12)

In [0]:
NUMBER_R=10

In [0]:
INCREMENT_R=1

In [0]:
optionS=np.array(np.arange(1,NUMBER_S+1,INCREMENT_S))

In [52]:
optionS

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [0]:
optionX=np.array(np.arange(1,NUMBER_X+1,INCREMENT_X))

In [54]:
optionX

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [0]:
optionR=np.array(np.arange(0,NUMBER_R+1,INCREMENT_R))

In [56]:
optionR

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
NUMBER_SIGMA=10

In [0]:
INCREMENT_SIGMA=1/1

In [59]:
INCREMENT_SIGMA

1.0

In [0]:
optionSIGMA=np.array(np.arange(1,NUMBER_SIGMA+1,INCREMENT_SIGMA))

In [61]:
optionSIGMA

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [0]:
optionT=(np.arange(-INCREMENT_T,NUMBER_T-INCREMENT_T,-INCREMENT_T))

In [63]:
optionT

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [0]:
NUMBER_OPTIONS=NUMBER_S*NUMBER_X*NUMBER_SIGMA*int(-NUMBER_T/INCREMENT_T)*(NUMBER_R+1)

In [65]:
print("{:,}".format(NUMBER_OPTIONS))

3,300,000


In [0]:
optionValue=np.zeros(NUMBER_OPTIONS)

In [0]:
#optionDF=pd.DataFrame(index=np.arange(0,NUMBER_OPTIONS,1),columns=["S","X","R","Sigma","Time","Value"])

In [68]:
optionDF.shape

(3300000, 6)

In [71]:
optionValue

array([0., 0., 0., ..., 0., 0., 0.])

In [72]:
optionValue.size

3300000

In [73]:
optionS.size

50

In [0]:
t=np.tile(optionT,NUMBER_OPTIONS//optionT.size)


In [75]:
t

array([ 21,  42,  63, ..., 210, 231, 252])

In [76]:
t[:25]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21])

In [77]:
t[-24:]

array([ 21,  42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252,  21,
        42,  63,  84, 105, 126, 147, 168, 189, 210, 231, 252])

In [78]:
t.size

3300000

In [0]:
r=np.tile(np.repeat(optionR,optionT.size),NUMBER_OPTIONS//(optionT.size*optionR.size))

In [80]:
r[0:500]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7

In [81]:
r.size

3300000

In [0]:
sig=np.tile(np.repeat(optionSIGMA,optionR.size*optionT.size),NUMBER_OPTIONS//(optionT.size*optionR.size*optionSIGMA.size))

In [83]:
sig[80:90]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
x=np.tile(np.repeat(optionX,optionT.size*optionR.size*optionSIGMA.size),NUMBER_OPTIONS//(optionX.size*optionT.size*optionR.size*optionSIGMA.size))

In [85]:
x

array([ 1.,  1.,  1., ..., 50., 50., 50.])

In [86]:
x.size

3300000

In [87]:
x[8350:8450]

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [0]:
s=np.repeat(optionS,NUMBER_OPTIONS/optionS.size)

In [89]:
 s.shape

(3300000,)

In [90]:
 s[8350:8450]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
v=np.zeros((NUMBER_OPTIONS))

In [0]:
optionDF6=pd.DataFrame(data={"S":s,"X":x,"Sigma":sig,"R":r,"T":t,"Value":v},index=np.arange(0,NUMBER_OPTIONS,1))

In [0]:
optionDF6=optionDF6[['S','X','Sigma','R','T','Value']]

In [95]:
optionDF6.shape

(3300000, 6)

In [96]:
pd.set_option('display.max_rows',1000)
print(optionDF6[:850])

       S    X  Sigma   R    T  Value
0    1.0  1.0    1.0   0   21    0.0
1    1.0  1.0    1.0   0   42    0.0
2    1.0  1.0    1.0   0   63    0.0
3    1.0  1.0    1.0   0   84    0.0
4    1.0  1.0    1.0   0  105    0.0
5    1.0  1.0    1.0   0  126    0.0
6    1.0  1.0    1.0   0  147    0.0
7    1.0  1.0    1.0   0  168    0.0
8    1.0  1.0    1.0   0  189    0.0
9    1.0  1.0    1.0   0  210    0.0
10   1.0  1.0    1.0   0  231    0.0
11   1.0  1.0    1.0   0  252    0.0
12   1.0  1.0    1.0   1   21    0.0
13   1.0  1.0    1.0   1   42    0.0
14   1.0  1.0    1.0   1   63    0.0
15   1.0  1.0    1.0   1   84    0.0
16   1.0  1.0    1.0   1  105    0.0
17   1.0  1.0    1.0   1  126    0.0
18   1.0  1.0    1.0   1  147    0.0
19   1.0  1.0    1.0   1  168    0.0
20   1.0  1.0    1.0   1  189    0.0
21   1.0  1.0    1.0   1  210    0.0
22   1.0  1.0    1.0   1  231    0.0
23   1.0  1.0    1.0   1  252    0.0
24   1.0  1.0    1.0   2   21    0.0
25   1.0  1.0    1.0   2   42    0.0
2

In [105]:
%%time
optionValue=bs(s,x,r/100,sig/100,t/BUSINESS_DAYS)

CPU times: user 797 ms, sys: 13.2 ms, total: 810 ms
Wall time: 813 ms


In [106]:
print("{:,}".format(optionValue.size))

3,300,000


In [92]:
print(optionValue[80000:80500])

[9.40781879 9.52722074 9.62174686 9.69682491 5.9113766  7.12095963
 7.92210241 8.48006899 8.87867026 9.16778794 9.37962139 9.53594722
 9.65193    9.73833891 9.80292815 9.851338   6.16876553 7.46166536
 8.27793138 8.81708752 9.18115742 9.43019007 9.60196907 9.7211555
 9.80420779 9.86227117 9.90296927 9.93155496 6.41696745 7.7742065
 8.58641879 9.09225579 9.41323005 9.61906172 9.75193642 9.83810135
 9.89415675 9.93071144 9.95459307 9.97021767 6.65522913 8.05808171
 8.84976948 9.31225758 9.58660633 9.75069563 9.84932435 9.90879615
 9.94473454 9.96648496 9.97966316 9.98765411 5.78281185 6.86271245
 7.58379135 8.10405308 8.49436718 8.79418952 9.02818113 9.21288822
 9.3599481  9.47782123 9.57280968 9.64969484 6.00369421 7.16203723
 7.91148949 8.43338286 8.81042809 9.08893897 9.29775014 9.45598672
 9.57686783 9.66979504 9.74159467 9.79730092 6.21959262 7.44465945
 8.20914083 8.72056021 9.07469617 9.32505697 9.50452542 9.63446249
 9.72924651 9.79879402 9.85006508 9.88800901 6.42991491 7.709557

In [0]:
optionDF6['Value']=optionValue

In [108]:
optionDF6

S     X  Sigma   R    T     Value
0         1.0   1.0    1.0   0   21  0.001152
1         1.0   1.0    1.0   0   42  0.001629
2         1.0   1.0    1.0   0   63  0.001995
3         1.0   1.0    1.0   0   84  0.002303
4         1.0   1.0    1.0   0  105  0.002575
5         1.0   1.0    1.0   0  126  0.002821
6         1.0   1.0    1.0   0  147  0.003047
7         1.0   1.0    1.0   0  168  0.003257
8         1.0   1.0    1.0   0  189  0.003455
9         1.0   1.0    1.0   0  210  0.003642
10        1.0   1.0    1.0   0  231  0.003820
11        1.0   1.0    1.0   0  252  0.003989
12        1.0   1.0    1.0   1   21  0.001615
13        1.0   1.0    1.0   1   42  0.002594
14        1.0   1.0    1.0   1   63  0.003485
15        1.0   1.0    1.0   1   84  0.004336
16        1.0   1.0    1.0   1  105  0.005166
17        1.0   1.0    1.0   1  126  0.005983
18        1.0   1.0    1.0   1  147  0.006792
19        1.0   1.0    1.0   1  168  0.007595
20        1.0   1.0    1.0   1  189  0.008394
21        1.0   1.0    1.0   1  210  0.009190
22        1.0   1.0    1.0   1  231  0.009985
23        1.0   1.0    1.0   1  252  0.010779
24        1.0   1.0    1.0   2   21  0.002170
25        1.0   1.0    1.0   2   42  0.003804
26        1.0   1.0    1.0   2   63  0.005403
27        1.0   1.0    1.0   2   84  0.006998
28        1.0   1.0    1.0   2  105  0.008597
29        1.0   1.0    1.0   2  126  0.010200
30        1.0   1.0    1.0   2  147  0.011808
31        1.0   1.0    1.0   2  168  0.013419
32        1.0   1.0    1.0   2  189  0.015033
33        1.0   1.0    1.0   2  210  0.016650
34        1.0   1.0    1.0   2  231  0.018267
35        1.0   1.0    1.0   2  252  0.019885
36        1.0   1.0    1.0   3   21  0.002805
37        1.0   1.0    1.0   3   42  0.005205
38        1.0   1.0    1.0   3   63  0.007618
39        1.0   1.0    1.0   3   84  0.010047
40        1.0   1.0    1.0   3  105  0.012487
41        1.0   1.0    1.0   3  126  0.014931
42        1.0   1.0    1.0   3  147  0.017376
43        1.0   1.0    1.0   3  168  0.019820
44        1.0   1.0    1.0   3  189  0.022261
45        1.0   1.0    1.0   3  210  0.024699
46        1.0   1.0    1.0   3  231  0.027131
47        1.0   1.0    1.0   3  252  0.029558
48        1.0   1.0    1.0   4   21  0.003505
49        1.0   1.0    1.0   4   42  0.006732
50        1.0   1.0    1.0   4   63  0.009992
51        1.0   1.0    1.0   4   84  0.013265
52        1.0   1.0    1.0   4  105  0.016538
53        1.0   1.0    1.0   4  126  0.019806
54        1.0   1.0    1.0   4  147  0.023066
55        1.0   1.0    1.0   4  168  0.026315
56        1.0   1.0    1.0   4  189  0.029555
57        1.0   1.0    1.0   4  210  0.032784
58        1.0   1.0    1.0   4  231  0.036003
59        1.0   1.0    1.0   4  252  0.039211
60        1.0   1.0    1.0   5   21  0.004254
61        1.0   1.0    1.0   5   42  0.008330
62        1.0   1.0    1.0   5   63  0.012432
63        1.0   1.0    1.0   5   84  0.016532
64        1.0   1.0    1.0   5  105  0.020619
65        1.0   1.0    1.0   5  126  0.024690
66        1.0   1.0    1.0   5  147  0.028746
67        1.0   1.0    1.0   5  168  0.032784
68        1.0   1.0    1.0   5  189  0.036806
69        1.0   1.0    1.0   5  210  0.040811
70        1.0   1.0    1.0   5  231  0.044799
71        1.0   1.0    1.0   5  252  0.048771
72        1.0   1.0    1.0   6   21  0.005036
73        1.0   1.0    1.0   6   42  0.009960
74        1.0   1.0    1.0   6   63  0.014890
75        1.0   1.0    1.0   6   84  0.019802
76        1.0   1.0    1.0   6  105  0.024690
77        1.0   1.0    1.0   6  126  0.029554
78        1.0   1.0    1.0   6  147  0.034395
79        1.0   1.0    1.0   6  168  0.039211
80        1.0   1.0    1.0   6  189  0.044003
81        1.0   1.0    1.0   6  210  0.048771
82        1.0   1.0    1.0   6  231  0.053515
83        1.0   1.0    1.0   6  252  0.058235
84        1.0   1.0    1.0   7   21  0.005839
85        1.0   1.0    1.0   7   42  0.011601
86        

In [0]:
f=open('optionDF6.csv', 'w')

In [0]:
optionDF6.to_csv('optionDF6.csv')

In [112]:
!pwd

/content


In [113]:
!ls -altr

total 142500
drwxr-xr-x 1 root root      4096 Dec 18 20:29 .config
drwxr-xr-x 1 root root      4096 Dec 18 20:29 sample_data
drwxr-xr-x 1 root root      4096 Dec 27 22:48 ..
drwxr-xr-x 1 root root      4096 Dec 27 23:13 .
-rw-r--r-- 1 root root 145902508 Dec 27 23:14 optionDF6.csv
