<a href="https://colab.research.google.com/github/dpnolan/learningBlackScholes/blob/master/LBS_Neural_Net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mount Google Drive in the virtual machine


In [215]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [216]:
%cd 'MyDrive/LearningBlackScholes'

/gdrive/MyDrive/LearningBlackScholes


In [217]:
!ls *.csv

lbs_3input_data.csv


In [218]:
import pandas as pd

In [219]:
option_df=pd.read_csv('lbs_3input_data.csv')

In [220]:
option_df

Unnamed: 0      S      X      Time    R  Sigma          Value
0               1    1.0    5.0  0.083333  0.1    0.2  6.649281e-172
1               2    2.0    5.0  0.083333  0.1    0.2   5.727005e-58
2               3    3.0    5.0  0.083333  0.1    0.2   4.015652e-20
3               4    4.0    5.0  0.083333  0.1    0.2   6.113758e-06
4               5    5.0    5.0  0.083333  0.1    0.2   1.366098e-01
...           ...    ...    ...       ...  ...    ...            ...
23995       23996   96.0  100.0  1.000000  0.1    0.2   1.050696e+01
23996       23997   97.0  100.0  1.000000  0.1    0.2   1.117037e+01
23997       23998   98.0  100.0  1.000000  0.1    0.2   1.185239e+01
23998       23999   99.0  100.0  1.000000  0.1    0.2   1.255237e+01
23999       24000  100.0  100.0  1.000000  0.1    0.2   1.326968e+01

[24000 rows x 7 columns]

In [221]:
option_df.columns

Index(['Unnamed: 0', 'S', 'X', 'Time', 'R', 'Sigma', 'Value'], dtype='object')

In [222]:
option_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24000 entries, 0 to 23999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  24000 non-null  int64  
 1   S           24000 non-null  float64
 2   X           24000 non-null  float64
 3   Time        24000 non-null  float64
 4   R           24000 non-null  float64
 5   Sigma       24000 non-null  float64
 6   Value       24000 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 1.3 MB


In [226]:
option_df=option_df.drop(labels='Unnamed: 0',axis=1)

KeyError: ignored

In [227]:
from tensorflow import keras

In [228]:
option_df.describe()

S             X          Time             R         Sigma  \
count  24000.000000  24000.000000  24000.000000  2.400000e+04  2.400000e+04   
mean      50.500000     52.500000      0.541667  1.000000e-01  2.000000e-01   
std       28.866671     28.832007      0.287677  1.387808e-17  2.775615e-17   
min        1.000000      5.000000      0.083333  1.000000e-01  2.000000e-01   
25%       25.750000     28.750000      0.312500  1.000000e-01  2.000000e-01   
50%       50.500000     52.500000      0.541667  1.000000e-01  2.000000e-01   
75%       75.250000     76.250000      0.770833  1.000000e-01  2.000000e-01   
max      100.000000    100.000000      1.000000  1.000000e-01  2.000000e-01   

              Value  
count  2.400000e+04  
mean   1.693901e+01  
std    2.304319e+01  
min    0.000000e+00  
25%    3.746567e-07  
50%    3.529242e+00  
75%    2.931601e+01  
max    9.547581e+01

In [229]:
X=option_df.drop(labels='Value',axis=1)

In [230]:
X

S      X      Time    R  Sigma
0        1.0    5.0  0.083333  0.1    0.2
1        2.0    5.0  0.083333  0.1    0.2
2        3.0    5.0  0.083333  0.1    0.2
3        4.0    5.0  0.083333  0.1    0.2
4        5.0    5.0  0.083333  0.1    0.2
...      ...    ...       ...  ...    ...
23995   96.0  100.0  1.000000  0.1    0.2
23996   97.0  100.0  1.000000  0.1    0.2
23997   98.0  100.0  1.000000  0.1    0.2
23998   99.0  100.0  1.000000  0.1    0.2
23999  100.0  100.0  1.000000  0.1    0.2

[24000 rows x 5 columns]

In [231]:
X.shape

(24000, 5)

In [233]:
XA=X.to_numpy(copy=True)

In [48]:
import numpy as np

In [238]:
XA.shape

(24000, 5)

In [237]:
XA

array([[1.00000000e+00, 5.00000000e+00, 8.33333333e-02, 1.00000000e-01,
        2.00000000e-01],
       [2.00000000e+00, 5.00000000e+00, 8.33333333e-02, 1.00000000e-01,
        2.00000000e-01],
       [3.00000000e+00, 5.00000000e+00, 8.33333333e-02, 1.00000000e-01,
        2.00000000e-01],
       ...,
       [9.80000000e+01, 1.00000000e+02, 1.00000000e+00, 1.00000000e-01,
        2.00000000e-01],
       [9.90000000e+01, 1.00000000e+02, 1.00000000e+00, 1.00000000e-01,
        2.00000000e-01],
       [1.00000000e+02, 1.00000000e+02, 1.00000000e+00, 1.00000000e-01,
        2.00000000e-01]])

In [239]:
XA[0]

array([1.        , 5.        , 0.08333333, 0.1       , 0.2       ])

In [163]:
Y=option_df['Value']

In [240]:
type(Y)

pandas.core.series.Series

In [241]:
Y

0        6.649281e-172
1         5.727005e-58
2         4.015652e-20
3         6.113758e-06
4         1.366098e-01
             ...      
23995     1.050696e+01
23996     1.117037e+01
23997     1.185239e+01
23998     1.255237e+01
23999     1.326968e+01
Name: Value, Length: 24000, dtype: float64

In [242]:
YA=Y.to_numpy(copy=True)

In [243]:
YA.argmax()

22099

In [244]:
option_df.iloc[22099]

S        100.000000
X          5.000000
Time       1.000000
R          0.100000
Sigma      0.200000
Value     95.475813
Name: 22099, dtype: float64

In [301]:
X.describe().transpose()[['mean', 'std']]

mean           std
S      50.500000  2.886667e+01
X      52.500000  2.883201e+01
Time    0.541667  2.876770e-01
R       0.100000  1.387808e-17
Sigma   0.200000  2.775615e-17

In [245]:
from math import log, sqrt, exp
from scipy import stats

In [246]:
from sklearn.preprocessing import StandardScaler

In [247]:
XT=StandardScaler().fit_transform(XA)

In [248]:
XT.shape

(24000, 5)

In [249]:
XT

array([[-1.71481604e+00, -1.64750894e+00, -1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17],
       [-1.68017329e+00, -1.64750894e+00, -1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17],
       [-1.64553055e+00, -1.64750894e+00, -1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17],
       ...,
       [ 1.64553055e+00,  1.64750894e+00,  1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17],
       [ 1.68017329e+00,  1.64750894e+00,  1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17],
       [ 1.71481604e+00,  1.64750894e+00,  1.59325501e+00,
        -1.38777878e-17, -2.77555756e-17]])

In [252]:
YT=StandardScaler().fit_transform(YA.reshape(-1,1))

In [300]:
YT

array([[-0.73511381],
       [-0.73511381],
       [-0.73511381],
       ...,
       [-0.22074768],
       [-0.19037   ],
       [-0.15924061]])

In [255]:
YT.shape

(24000, 1)

In [256]:
from keras.models import Sequential
from keras.layers import Dense
# create model
model = Sequential()
model.add(Dense(4, input_dim=5, activation='sigmoid'))
model.add(Dense(1, activation='linear'))

In [257]:
import matplotlib.pyplot as plt

In [258]:
from keras.optimizers import SGD

In [259]:
opt=SGD(learning_rate=0.1)

In [260]:
from tensorflow.keras import layers

In [303]:
model.compile(loss='mse', optimizer=opt,metrics=['mse'])

# model.compile(optimizer="rmsprop", loss="mse", metrics=["mae"])

In [304]:
model.fit(XT, YT,epochs=30)

Epoch 1/30
750/750 [==============================] - 2s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 2/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 3/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 4/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 5/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 6/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 7/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 8/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 9/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 10/30
750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082
Epoch 11/30
750/750 [============================

In [280]:
scores = model.evaluate(XT, YT, verbose=2)
print("%s: %.2f" % (model.metrics_names[0], scores[0]))

750/750 - 1s - loss: 0.0082 - mse: 0.0082 - 915ms/epoch - 1ms/step
loss: 0.01


In [281]:
XT[22099]

array([ 1.71481604e+00, -1.64750894e+00,  1.59325501e+00, -1.38777878e-17,
       -2.77555756e-17])

In [282]:
Y.iloc[22099]

95.4758129098202

In [283]:
YT[22099]

array([3.40831518])

S        100.000000
X          5.000000
Time       1.000000
R          0.100000
Sigma      0.200000
Value     95.475813

In [285]:
model.evaluate(XT,YT)

750/750 [==============================] - 1s 2ms/step - loss: 0.0082 - mse: 0.0082


[0.008156643249094486, 0.008156643249094486]

In [270]:
model.predict(XT)[22099]

750/750 [==============================] - 1s 1ms/step


array([4.338914], dtype=float32)

In [271]:
Y.mean()

16.939010907365937

In [272]:
Y.std()

23.043185273941155

In [273]:
YT.mean()

2.3684757858670008e-17

In [274]:
YT.std()

1.0

In [275]:
XT[22099]

array([ 1.71481604e+00, -1.64750894e+00,  1.59325501e+00, -1.38777878e-17,
       -2.77555756e-17])

In [287]:
YT[22099]

array([3.40831518])

In [289]:
3.40831518*Y.std()+Y.mean()

95.47744907209204

In [295]:
Y_hat=(model.predict(XT)[22099])

750/750 [==============================] - 3s 3ms/step


In [296]:
Y_hat

array([2.9388366], dtype=float32)

In [302]:
Y_hat*Y.std()+Y.mean()

array([84.65917], dtype=float32)